name: release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate some data
        run: |
          mkdir build
          echo "test 2" > build/index.html

      - uses: aquiladev/ipfs-action@v0.3.1
        with:
          path: ./build
          timeout: 300000
          service: ipfs
          pin: true
          host: ipfs-api.apyos.dev
          protocol: https
          port: 443
          headers: '{ "Authorization": "${{ secrets.IPFS_AUTHORIZATION }}" }'
          key: kurate
