name: release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate some data
        run: |
          mkdir build
          echo "test" > build/index.html

      - uses: aquiladev/ipfs-action@v0.3.1
        with:
          path: ./build
          service: ipfs
          pin: true
          host: ipfs.apyos.dev
          headers: '{ "Authorization": "${{ secrets.IPFS_AUTHORIZATION }}" }'
          key: kurate
